name: Psalm Security Scan (SARIF & JSON Reports)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '16 22 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  php-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, xml, pdo, pdo_mysql
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run Psalm Static Analysis (Generate SARIF)
        uses: psalm/psalm-github-actions@2.3.0
        with:
          security_analysis: true
          show_info: false
          composer_require_dev: true
          report_file: results.sarif
          args: --output-format=sarif

      - name: Run Psalm Static Analysis (Generate JSON)
        uses: psalm/psalm-github-actions@2.3.0
        with:
          security_analysis: true
          show_info: false
          composer_require_dev: true
          report_file: results.json
          args: --output-format=json

      - name: Upload SARIF results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Upload JSON Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: psalm-json-report
          path: results.json
