name: Semgrep Security Scan

on:
  push:
    branches: [ "main", "master", "next" ]
  pull_request:
    branches: [ "main", "master", "next" ]

jobs:
  semgrep-scan:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python -m pip install semgrep
          semgrep --version
      # --- PHP Security Scan (p/php) ---
      - name: Run Semgrep Scan (PHP, SARIF Output)
        run: |
          semgrep --config=p/php --sarif --output=semgrep-php.sarif .
      - name: Run Semgrep Scan (PHP, JSON Output)
        run: |
          semgrep --config=p/php --json --output=semgrep-php.json .
      # --- Secrets Scan (p/secrets) ---
      - name: Run Semgrep Scan (Secrets, SARIF Output)
        run: |
          semgrep --config=p/secrets --sarif --output=semgrep-secrets.sarif .
      - name: Run Semgrep Scan (Secrets, JSON Output)
        run: |
          semgrep --config=p/secrets --json --output=semgrep-secrets.json .
      # --- Upload SARIF results to GitHub Code Scanning ---
      - name: Upload PHP SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-php.sarif
          category: semgrep-php
        if: always()

      - name: Upload Secrets SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-secrets.sarif
          category: semgrep-secrets
        if: always()

      # --- Upload all reports as artifact ---
      - name: Upload Semgrep Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-security-reports
          path: |
            semgrep-php.sarif
            semgrep-php.json
            semgrep-secrets.sarif
            semgrep-secrets.json
        if: always()
